(()=>{
  'use strict';
  const c=window.SUBJECT_CONFIG;
  if(!c) throw new Error('SUBJECT_CONFIG is required');
  const DEFAULT_STATE={answers:0,correct:0,wrong:[],tasks:[],last:''};
  let storageAvailable=true;
  function load(){try{const v=JSON.parse(localStorage.getItem(c.storageKey)||'null');if(!v||typeof v!=='object')return{...DEFAULT_STATE};return{answers:Number.isFinite(v.answers)?v.answers:0,correct:Number.isFinite(v.correct)?v.correct:0,wrong:Array.isArray(v.wrong)?v.wrong.filter(Number.isInteger):[],tasks:Array.isArray(v.tasks)?v.tasks.filter(Number.isInteger):[],last:typeof v.last==='string'?v.last:''}}catch(e){storageAvailable=false;return{...DEFAULT_STATE}}}
  let state=load(),qi=0,answered=false;
  const $=id=>document.getElementById(id);
  function save(){state.last=new Date().toDateString();try{localStorage.setItem(c.storageKey,JSON.stringify(state))}catch(e){storageAvailable=false}$('storageNotice').classList.toggle('hide',storageAvailable);renderStats()}
  function shell(){
    document.documentElement.style.setProperty('--accent',c.colors[0]);document.documentElement.style.setProperty('--accent2',c.colors[1]);
    document.title=`${c.shortName}通关台 · 2026`;
    $('app').innerHTML=`<div class="app"><aside class="sidebar"><div class="brand"><div class="seal">${c.shortName}</div><div><strong>通关学习台</strong><span>2026 · CTA</span></div></div><nav class="nav" aria-label="主导航">${navButtons(false)}</nav><div class="policy">政策口径截止：2026-03-31<br>数据仅保存在当前浏览器</div></aside><main class="main"><header class="topbar"><div><div class="eyebrow">2026 税务师 · ${c.title}</div><h1 id="pageTitle">今日学习</h1><div class="date" id="todayDate"></div></div><div class="pill">三科备考 · 独立进度</div></header><div class="notice hide" id="storageNotice" role="status">当前浏览器无法保存学习进度。页面仍可使用，但刷新后本次记录可能丢失。</div>${views()}</main></div><nav class="mobile-nav" aria-label="移动端导航">${navButtons(true)}</nav>`;
  }
  function navButtons(short){const labels=short?['今日','知识树','练习','错题','计划','说明','备查']:['今日学习','完整知识树','5 道练习题','错题本','四阶段计划','大纲与说明','备查资料'];return ['home','chapters','quiz','wrong','plan','about','sources'].map((id,i)=>`<button ${i?'':'class="active"'} data-view="${id}">${labels[i]}</button>`).join('')}
  function views(){return `<section class="view active" id="home"><div class="dashboard"><div><article class="card today" data-mark="${c.mark}"><div class="tag">今日主线 · ${c.today.tag}</div><h2>${c.today.title}</h2><p>${c.today.text}</p><div class="actions"><button class="primary" data-go="quiz">开始 5 题练习</button><button class="ghost" data-go="chapters">查看完整知识树</button></div></article><div class="kpis"><div class="kpi"><span>连续学习</span><strong>1 天</strong></div><div class="kpi"><span>累计答题</span><strong id="answerCount">0</strong></div><div class="kpi"><span>当前正确率</span><strong id="accuracy">—</strong></div></div></div><aside class="card"><div class="mini-title">总体掌握度</div><div class="ring" id="ring" style="--p:0%"><strong id="mastery">0%</strong></div><div class="mini-title">四阶段完成度</div><div class="progress"><i id="weekBar"></i></div><p id="weekText" class="source-meta"></p><hr style="border:0;border-top:1px solid var(--line);margin:20px 0"><b>学习比重说明</b><p class="source-meta">${c.weightNote}</p></aside></div></section>
    <section class="view" id="chapters"><div class="section-head"><h2>完整知识树</h2><span class="source-meta">共 ${c.chapters.length} 章</span></div><div class="notice">注意力比重综合两份辅导资料中的历史命题分布，并按 2026 官方大纲校正；它是复习时间建议，不是官方分值预测。</div><div class="chapter-grid" id="chapterGrid"></div></section>
    <section class="view" id="quiz"><div class="quiz-layout"><article class="card question"><small id="qMeta"></small><h3 id="qText"></h3><div class="options" id="options"></div><button class="primary" id="submitAnswer">提交答案</button><div class="feedback" id="feedback"></div></article><aside class="card"><div class="mini-title">今日练习进度</div><h2><span id="qIndex">1</span> / 5</h2><div class="progress"><i id="qBar"></i></div><p class="source-meta">题目用于训练判断路径，不替代官方教材、法规原文或正式题库。</p><button class="danger" id="resetQuiz">重新练习</button></aside></div></section>
    <section class="view" id="wrong"><div class="section-head"><h2>错题本</h2><button class="danger" id="clearWrong">清空错题</button></div><div id="wrongList" class="wrong-list"></div></section>
    <section class="view" id="plan"><div class="section-head"><h2>四阶段计划</h2></div><div class="plan-grid" id="planGrid"></div></section>
    <section class="view" id="about"><div class="card"><h2>2026 年大纲口径</h2>${c.about.map(x=>`<p>${x}</p>`).join('')}<div class="notice">本系统是备考辅助工具，不构成税务、法律或执业意见。实际业务和考试学习请核验最新有效的法律法规及官方教材。</div></div></section>
    <section class="view" id="sources"><div class="section-head"><h2>学习备查资料</h2></div><div class="notice info">本页优先链接官方原文。第三方页面仅作为目录线索；已将与本科相关的标题和官方链接整理到本地，避免依赖其页面运行或变更。</div><div class="source-groups">${c.sources.map(g=>`<article class="card source-group"><h3>${g.title}</h3><ul class="source-list">${g.items.map(x=>`<li><a href="${x[1]}" target="_blank" rel="noopener noreferrer">${x[0]}</a></li>`).join('')}</ul></article>`).join('')}</div><p class="source-meta">目录来源：<a href="https://williamjiamin.github.io/simple-tax-advisor-site/sources.html" target="_blank" rel="noopener noreferrer">税务实用工具箱 · 政策原文入口</a>（页面标注更新于 2026-07-13）。链接有效性及政策时效以发布机关为准。</p></section>`}
  const titles={home:'今日学习',chapters:'完整知识树',quiz:'5 道练习题',wrong:'错题本',plan:'四阶段计划',about:'大纲与说明',sources:'备查资料'};
  function go(id){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===id));$('pageTitle').textContent=titles[id];if(id==='wrong')renderWrong();scrollTo(0,0)}
  function renderChapters(){$('chapterGrid').innerHTML=c.chapters.map((x,i)=>`<article class="chapter"><div class="chapter-head"><div><span style="color:var(--accent);font-size:13px">第${i+1}章</span><br><b>${x.title}</b></div><span class="level">${x.weight>=20?'核心':'按大纲'}</span></div><p>${x.desc}</p><div class="progress"><i style="width:${Math.min(100,x.weight*2.5)}%"></i></div><footer><span>建议精力</span><strong>${x.weight}%</strong></footer></article>`).join('')}
  function renderQuiz(){const q=c.questions[qi];answered=false;$('qMeta').textContent=q.meta;$('qText').textContent=q.q;$('options').innerHTML=q.options.map((x,i)=>`<label class="option"><input type="radio" name="ans" value="${i}"><span><b>${String.fromCharCode(65+i)}.</b> ${x}</span></label>`).join('');$('feedback').className='feedback';$('submitAnswer').textContent='提交答案';$('qIndex').textContent=qi+1;$('qBar').style.width=((qi+1)/c.questions.length*100)+'%'}
  function submit(){if(answered){qi=(qi+1)%c.questions.length;renderQuiz();return}const picked=document.querySelector('input[name=ans]:checked');if(!picked){alert('请先选择一个答案');return}const q=c.questions[qi],ok=+picked.value===q.answer;state.answers++;if(ok)state.correct++;else if(!state.wrong.includes(qi))state.wrong.push(qi);save();answered=true;const f=$('feedback');f.className='feedback show';f.style.borderColor=ok?'var(--accent2)':'var(--red)';f.innerHTML=`<b>${ok?'回答正确':'答案是 '+String.fromCharCode(65+q.answer)}</b><br>${q.explain}`;$('submitAnswer').textContent=qi===c.questions.length-1?'回到第一题':'下一题'}
  function renderWrong(){$('wrongList').innerHTML=state.wrong.length?state.wrong.map((n,pos)=>{const q=c.questions[n];return q?`<article class="wrong"><b>${q.meta}</b><h3>${q.q}</h3><p>正确答案：${String.fromCharCode(65+q.answer)} · ${q.options[q.answer]}</p><p>${q.explain}</p><button class="danger" data-remove-wrong="${pos}">已掌握</button></article>`:''}).join(''):'<div class="card empty">还没有错题。完成 5 道练习后，错题会自动收录到这里。</div>';document.querySelectorAll('[data-remove-wrong]').forEach(b=>b.onclick=()=>{state.wrong.splice(+b.dataset.removeWrong,1);save();renderWrong()})}
  function renderPlan(){$('planGrid').innerHTML=c.tasks.map((t,i)=>`<article class="card task ${state.tasks.includes(i)?'done':''}"><input id="task${i}" type="checkbox" ${state.tasks.includes(i)?'checked':''}><label for="task${i}"><b>${t[0]}</b><br><span class="source-meta">${t[1]}</span></label></article>`).join('');c.tasks.forEach((_,i)=>{$('task'+i).onchange=()=>{state.tasks=state.tasks.includes(i)?state.tasks.filter(x=>x!==i):[...state.tasks,i];save();renderPlan()}})}
  function renderStats(){const acc=state.answers?Math.round(state.correct/state.answers*100):0,mastery=Math.min(100,Math.round((state.answers/50)*60+(state.tasks.length/4)*40));$('answerCount').textContent=state.answers;$('accuracy').textContent=state.answers?acc+'%':'—';$('mastery').textContent=mastery+'%';$('ring').style.setProperty('--p',mastery+'%');$('weekBar').style.width=(state.tasks.length/4*100)+'%';$('weekText').textContent=`已完成 ${state.tasks.length} / 4 个阶段任务`}
  shell();$('todayDate').textContent=new Intl.DateTimeFormat('zh-CN',{dateStyle:'full'}).format(new Date());$('storageNotice').classList.toggle('hide',storageAvailable);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('submitAnswer').onclick=submit;$('resetQuiz').onclick=()=>{qi=0;renderQuiz()};$('clearWrong').onclick=()=>{if(state.wrong.length&&confirm('确认清空全部错题？')){state.wrong=[];save();renderWrong()}};renderChapters();renderQuiz();renderPlan();renderStats();
})();
