function renderNotices(){
  const groups=[['收入与税额核对',[0,1,2,11,12]],['制单与开票',[3,5,7,8,9,10]],['特殊情况处理',[4,6]]];
  document.getElementById('noticeList').innerHTML=groups.map(([title,indexes])=>`<div class="notice-group"><h3>${title}</h3>${indexes.map(i=>`<details class="notice-entry"><summary>${escapeHTML(NOTICES[i].title)}</summary><p>${escapeHTML(NOTICES[i].body).replace(/\n/g,'<br>')}</p></details>`).join('')}</div>`).join('');
}
function toggleNotice(i){const el=document.querySelectorAll('.notice-entry')[i];if(el)el.open=!el.open;}
function renderTaxGrid(){const container=document.getElementById('taxGrid');if(!container)return;container.innerHTML=TAX_COMPANIES.map(c=>`<button type="button" class="tax-item${state.tax[c.id]?.done?' done':''}${!c.active?' cancelled':''}" ${!c.active?'disabled':`onclick="toggleTax(${c.id})"`} aria-pressed="${!!state.tax[c.id]?.done}"><span class="tx-name">${escapeHTML(c.short)}</span><span class="tx-status">${!c.active?escapeHTML(c.note):state.tax[c.id]?.done?'已完成 · 点击撤销':'待申报 · 核实后标记'}</span><small>${escapeHTML(c.freq)}</small></button>`).join('');updateTaxProgress();}
function toggleTax(id){if(!TAX_COMPANIES.some(c=>c.id===id&&c.active))return;state.tax[id]={...state.tax[id],done:!state.tax[id]?.done,updatedAt:new Date().toISOString()};saveData();renderTaxGrid();}
function updateTaxProgress(){const rows=TAX_COMPANIES.filter(c=>c.active),done=rows.filter(c=>state.tax[c.id]?.done).length;const el=document.getElementById('taxMini');if(el)el.textContent='税务已完成 '+done+'/'+rows.length;}
function renderZakouGrid(){const el=document.getElementById('zakouGrid');if(!el)return;const n=ZAKOU_COMPANIES.filter((c,i)=>state.tasks['zakou_'+i]).length;el.innerHTML='<p class="section-hint" style="grid-column:1/-1">'+state.activePeriod+' · 已完成 '+n+'/'+ZAKOU_COMPANIES.length+' 家</p><div class="zakou-items">'+ZAKOU_COMPANIES.map((name,i)=>`<label class="zakou-row"><input type="checkbox" ${state.tasks['zakou_'+i]?'checked':''} onchange="toggleZakou(${i})"><span><strong>${escapeHTML(name)}</strong><small>${state.tasks['zakou_'+i]?'本期扎口已完成':'银行对账 / 利息 / 销项税 / 平账'}</small></span></label>`).join('')+'</div>';}
function toggleZakou(i){if(!Number.isInteger(i)||i<0||i>=ZAKOU_COMPANIES.length)return;state.tasks['zakou_'+i]=!state.tasks['zakou_'+i];saveData();renderZakouGrid();}
function renderStatistics(){for(let i=1;i<=3;i++){const el=document.getElementById('stat'+i);if(el){const done=!!state.tasks['stat_'+i];el.classList.toggle('done',done);el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-pressed',done);el.querySelector('.tx-status').textContent=done?'已申报 · 点击撤销':'待申报 · 统计云+电子台账';el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggleStat(i);}};}}}
function toggleStat(id){if(![1,2,3].includes(id))return;state.tasks['stat_'+id]=!state.tasks['stat_'+id];saveData();renderStatistics();}
function issueItems(){return UNRESOLVED.map((u,i)=>({key:'unresolved:'+u.proj+':'+u.item,code:u.proj,title:u.item,amount:u.amount,original:u.status})).concat(TAX_DIFFS.map(d=>({key:'taxdiff:'+d.code,code:d.code,title:'暂估销项税差 · '+d.name,amount:d.diff.toLocaleString('zh-CN',{minimumFractionDigits:2}),original:d.note})));}
function getHistoricalProjectStatus(code){const rows=issueItems().filter(i=>i.code===code),closed=rows.filter(i=>state.unresolvedRecords[i.key]?.status==='closed').length;return{total:rows.length,closed,open:rows.length-closed};}
function renderUnresolved(){
  const el=document.getElementById('unresolvedList');if(!el)return;
  const query=document.getElementById('issueSearch')?.value.trim().toLowerCase()||'',filter=document.getElementById('issueFilter')?.value||'open';
  const items=issueItems(),visible=items.map((u,i)=>({u,i,r:state.unresolvedRecords[u.key]||{}})).filter(({u,r})=>(!query||(u.code+' '+u.title).toLowerCase().includes(query))&&(filter==='all'||(filter==='closed'?r.status==='closed':r.status!=='closed')));
  document.getElementById('issueCount').textContent='显示 '+visible.length+' / '+items.length+' 项';
  el.innerHTML=visible.map(({u,i,r})=>{const s=r.status||'pending';return `<details class="issue-row" id="issueRow${i}"><summary><span><strong>${escapeHTML(u.code)}</strong> ${escapeHTML(u.title)}</span><span class="status-pill ${s==='closed'?'done':s==='working'?'working':'prepare'}">${s==='closed'?'已办结':s==='working'?'跟进中':'未处理'}</span></summary><p class="dialog-help">原交接金额：${escapeHTML(u.amount)} · 原交接说明：${escapeHTML(u.original)}</p><div class="issue-fields"><label>处理状态<select id="issueStatus${i}"><option value="pending" ${s==='pending'?'selected':''}>未处理</option><option value="working" ${s==='working'?'selected':''}>跟进中</option><option value="closed" ${s==='closed'?'selected':''}>已办结</option></select></label><label>下次跟进<input type="date" id="issueDate${i}" value="${escapeHTML(r.date||'')}"></label><label class="issue-note">处理备注<input id="issueNote${i}" maxlength="2000" value="${escapeHTML(r.note||'')}" placeholder="记录实际进展、联系情况或办结依据"></label><button class="btn btn-outline btn-sm" onclick="saveIssue(${i})">保存跟进</button></div>${r.updatedAt?'<p class="section-hint">最近记录：'+escapeHTML(new Date(r.updatedAt).toLocaleString('zh-CN'))+'</p>':''}</details>`;}).join('')||'<p class="empty-state">暂无匹配事项。已办结记录可切换筛选查看。</p>';
}
function saveIssue(index){const item=issueItems()[index];if(!item)return;const status=document.getElementById('issueStatus'+index).value;if(!['pending','working','closed'].includes(status))return;state.unresolvedRecords[item.key]={status,date:document.getElementById('issueDate'+index).value,note:document.getElementById('issueNote'+index).value.trim(),updatedAt:new Date().toISOString()};if(saveData()){renderUnresolved();const row=document.getElementById('issueRow'+index);if(row)row.open=true;renderFollowups();showToast(status==='closed'?'已办结，记录保留在“已办结”筛选中':'历史事项跟进已保存，不受月份切换影响');}}
function getUnresolvedFollowups(){return issueItems().flatMap(u=>{const r=state.unresolvedRecords[u.key];return r&&r.status!=='closed'&&(r.date||r.status==='working')?[{name:u.code+' · '+u.title,contact:'',detail:r.note||u.original,date:r.date||'',source:'extra'}]:[];});}
