const PROJECT_STATUS={pending:'未开始',working:'处理中',waiting:'待资料',review:'待复核',done:'已完成',na:'本月无需处理'};
function getProjectRecord(code){const p=state.projects[code];return isRecord(p)?{...p,status:Object.hasOwn(PROJECT_STATUS,p.status)?p.status:'pending'}:{status:'pending'};}
function projectSummary(){const rows=PROJECTS.map(p=>getProjectRecord(p.code));const done=rows.filter(r=>r.status==='done').length,excluded=rows.filter(r=>r.status==='na').length;return {total:rows.length-excluded,done,excluded,pending:rows.length-excluded-done,waiting:rows.filter(r=>r.status==='waiting').length};}
function readProjectFilters(){renderProjects();}
function projectStateOptions(value){return Object.entries(PROJECT_STATUS).map(([k,v])=>`<option value="${k}" ${k===value?'selected':''}>${v}</option>`).join('');}
function renderProjects(){
  const el=document.getElementById('projTbody');if(!el)return;
  const q=document.getElementById('projectSearch').value.trim().toLowerCase(),dept=document.getElementById('projectDeptFilter').value,biz=document.getElementById('projectBizFilter').value,status=document.getElementById('projectStatusFilter').value;
  const proxy=document.getElementById('projectProxyFilter').checked,unresolved=document.getElementById('projectUnresolvedFilter').checked;
  const rows=PROJECTS.filter(p=>{
    const r=getProjectRecord(p.code),s=r.status||'pending',historyOpen=p.unresolved?getHistoricalProjectStatus(p.code).open:0;
    return (!q||[p.code,p.name,p.contact].some(t=>t.toLowerCase().includes(q)))&&(dept==='all'||p.dept.includes(dept))&&(biz==='all'||(biz==='第三方'?(p.notes+p.settlement).includes('第三方'):biz==='unknown'?!p.type:p.type.includes(biz)))&&(!proxy||p.isProxy)&&(!unresolved||historyOpen>0)&&(status==='all'||(status==='unfinished'?!['done','na'].includes(s):s===status));
  }).sort((a,b)=>Number(['done','na'].includes(getProjectRecord(a.code).status))-Number(['done','na'].includes(getProjectRecord(b.code).status)));
  el.innerHTML=rows.map(p=>{const r=getProjectRecord(p.code),status=r.status||'pending',historyOpen=p.unresolved?getHistoricalProjectStatus(p.code).open:0;return `<tr><td><span class="project-title">${escapeHTML(p.name)}</span><span class="project-meta project-code">${p.code}${p.isProxy?' · 代管':''}</span></td><td>${escapeHTML(p.dept)}<span class="project-meta">${escapeHTML(p.contact)} · 成本：${escapeHTML(p.costAcc)}</span></td><td>${escapeHTML(p.type||'待补充')}</td><td><select class="project-status-select status-${escapeHTML(status)}" aria-label="${escapeHTML(p.name)}本月收入状态" onchange="setProjectStatus('${p.code}',this.value)">${projectStateOptions(status)}</select>${r.completedAt?`<span class="project-meta">完成于 ${escapeHTML(new Date(r.completedAt).toLocaleDateString('zh-CN'))}</span>`:''}</td><td><button class="text-button" onclick="openProjectDetail('${p.code}')">查看 / 记录</button>${p.unresolved?`<span class="project-meta" style="color:var(--amber)">${historyOpen>0?'历史未了 · '+historyOpen+'项':'历史事项已办结 · 可查看'}</span>`:''}${r.followupDate?'<span class="project-meta">跟进 '+escapeHTML(r.followupDate)+'</span>':''}</td></tr>`;}).join('')||'<tr><td colspan="5" class="empty-state">没有匹配项目。可清除筛选或修改关键词。</td></tr>';
  const summary=projectSummary();document.getElementById('projectSummary').innerHTML=`<span><strong>${summary.done}/${summary.total}</strong>本期已完成</span><span><strong>${summary.waiting}</strong>待资料</span><span><strong>${summary.excluded}</strong>本月无需处理</span>`;
  document.getElementById('projectFilterCount').textContent='显示 '+rows.length+' / '+PROJECTS.length+' 个项目 · '+state.activePeriod;
}
function filterProjects(filter){['projectDeptFilter','projectBizFilter','projectStatusFilter'].forEach(id=>document.getElementById(id).value='all');document.getElementById('projectSearch').value='';document.getElementById('projectProxyFilter').checked=filter==='代管';document.getElementById('projectUnresolvedFilter').checked=filter==='未了';if(['职能部门','一分部','二分部','三分部','五分部','六分部'].includes(filter))document.getElementById('projectDeptFilter').value=filter;if(['差额结算','人员服务','全额结算','第三方'].includes(filter))document.getElementById('projectBizFilter').value=filter;renderProjects();}
function updateProjectFilterButtons(){}
function setProjectStatus(code,status){
  if(!PROJECTS.some(p=>p.code===code)||!Object.hasOwn(PROJECT_STATUS,status))return;
  const old=getProjectRecord(code);state.projects[code]={...old,status,updatedAt:new Date().toISOString(),completedAt:status==='done'?(old.completedAt||new Date().toISOString()):null};saveData();refreshWorkspace();
}
function openProjectDetail(code){
  const p=PROJECTS.find(p=>p.code===code);if(!p)return;const r=getProjectRecord(code),dialog=document.getElementById('projectDetailDialog');dialog.dataset.code=code;dialog.dataset.period=state.activePeriod;
  dialog.innerHTML=`<div class="detail-header"><div><h2 id="projectDetailTitle">${escapeHTML(p.name)}</h2><p class="detail-period">${p.code} · 工作月份 ${state.activePeriod}</p></div><button class="btn btn-outline btn-sm" onclick="this.closest('dialog').close()">关闭</button></div><div class="detail-body"><dl class="detail-meta-grid"><div><dt>分部 / 对接人</dt><dd>${escapeHTML(p.dept)} / ${escapeHTML(p.contact)}</dd></div><div><dt>业务类型 / 成本会计</dt><dd>${escapeHTML(p.type||'待补充')} / ${escapeHTML(p.costAcc)}</dd></div><div class="detail-wide"><dt>核算要点</dt><dd>${escapeHTML(p.notes||'暂无特殊规则')}</dd></div><div class="detail-wide"><dt>结算与账期</dt><dd>${escapeHTML(p.settlement||'按实际项目资料确认')}</dd></div></dl><form onsubmit="event.preventDefault();saveProjectDetail()"><div class="detail-form"><label>本月收入状态<select id="projectDetailStatus">${projectStateOptions(r.status||'pending')}</select></label><label>下次跟进日期<input type="date" id="projectFollowupDate" value="${escapeHTML(r.followupDate||'')}"></label><label class="detail-wide">缺失资料 / 等待事项<input id="projectMissing" maxlength="500" value="${escapeHTML(r.missing||'')}" placeholder="例如：缺签字版结算单"></label><label class="detail-wide">本月处理备注<textarea id="projectNote" maxlength="3000">${escapeHTML(r.note||'')}</textarea></label></div>${p.unresolved?`<div class="detail-history"><strong>历史未了 · 不随月度完成清除</strong><p>${escapeHTML(p.unresolved)}</p><button type="button" class="text-button" onclick="this.closest('dialog').close();switchTab('extra')">查看历史事项跟进 →</button></div>`:''}<div class="detail-actions"><span class="detail-save-note">按 ${state.activePeriod} 保存，可修改或撤销完成。</span><button class="btn btn-pri" type="submit">保存本月记录</button></div></form></div>`;
  if(!dialog.open)dialog.showModal();
}
function saveProjectDetail(){
  const dialog=document.getElementById('projectDetailDialog'),code=dialog.dataset.code,period=dialog.dataset.period;
  if(period!==state.activePeriod){showToast('月份已变更，请重新打开项目详情');return;}
  const status=document.getElementById('projectDetailStatus').value,old=getProjectRecord(code);if(!Object.hasOwn(PROJECT_STATUS,status))return;
  state.projects[code]={...old,status,note:document.getElementById('projectNote').value.trim(),missing:document.getElementById('projectMissing').value.trim(),followupDate:document.getElementById('projectFollowupDate').value,updatedAt:new Date().toISOString(),completedAt:status==='done'?(old.completedAt||new Date().toISOString()):null};
  if(saveData()){dialog.close();refreshWorkspace();showToast('项目本月记录已保存');}
}
function getProjectFollowups(){return PROJECTS.flatMap(p=>{const r=getProjectRecord(p.code),needsFollowup=!['done','na'].includes(r.status)&&(r.followupDate||r.status==='waiting');return needsFollowup?[{code:p.code,name:p.name,contact:p.contact,detail:r.missing||r.note||'待补充资料',date:r.followupDate||'',source:'project'}]:[];});}
