const REPORT_WORKFLOW_STAGES={prepare:{label:'待资料',hint:'补齐资料与口径'},drafting:{label:'编制中',hint:'编制并核对数据'},review:{label:'待复核',hint:'交复核人复核'},reviewed:{label:'已复核',hint:'确认报送版本'},submitted:{label:'已提交',hint:'留存提交记录'}};
function getReportWorkflowStage(id){const s=state.reportWorkflow[id];return Object.hasOwn(REPORT_WORKFLOW_STAGES,s)?s:'prepare';}
function getReportShortName(r){return r.name.replace('科桥餐饮公司','餐饮').replace('科桥餐饮项目','餐饮项目');}
function renderReportCards(){
  document.getElementById('reportPeriodCaption').textContent='工作月份 '+state.activePeriod;
  document.getElementById('reportCardsList').innerHTML=REPORTS.map(r=>{const s=getReportWorkflowStage(r.id),m=REPORT_WORKFLOW_STAGES[s];return `<details class="report-row" id="reportCard${r.id}"><summary><div><h3>${r.id}. ${escapeHTML(getReportShortName(r))}</h3><small>报送：${escapeHTML(r.recipient)}</small></div><span class="status-pill ${s}">${m.label}</span><small>下一步：${m.hint}</small></summary><div class="report-details"><p>${escapeHTML(r.desc)}</p><div class="report-controls"><label>实际处理阶段 <select onchange="setReportStage(${r.id},this.value)">${Object.entries(REPORT_WORKFLOW_STAGES).map(([k,v])=>`<option value="${k}" ${k===s?'selected':''}>${v.label}</option>`).join('')}</select></label><button class="btn btn-outline btn-sm" onclick="openAIHandoff(${r.id})">去 AI 办理</button><button class="text-button" onclick="document.getElementById('checklistSection').scrollIntoView({behavior:'smooth'})">检查要点</button></div><p class="section-hint">仅记录你确认的进度。${state.reports[r.id].updatedAt?'最近更新：'+escapeHTML(new Date(state.reports[r.id].updatedAt).toLocaleString('zh-CN')):''}</p></div></details>`;}).join('');
  updateReportProgress();renderChecklist();renderAIStatus();
}
function setReportStage(id,stage){if(!REPORTS.some(r=>r.id===id)||!Object.hasOwn(REPORT_WORKFLOW_STAGES,stage))return;state.reportWorkflow[id]=stage;state.reports[id]={...state.reports[id],done:stage==='submitted',updatedAt:new Date().toISOString()};saveData();refreshWorkspace();document.getElementById('reportCard'+id).open=true;}
function updateReportProgress(){const n=REPORTS.filter(r=>getReportWorkflowStage(r.id)==='submitted').length;const el=document.getElementById('reportProgress');if(el)el.textContent='报表已提交 '+n+'/7';}
function openReportWorkspace(id){switchTab('reports');const card=document.getElementById('reportCard'+id);if(card){card.open=true;card.scrollIntoView({behavior:'smooth',block:'center'});}}
const CHECK_GROUPS=[['数据准确性',['各项目营业额与报账员确认一致','差额营业额 = 营业额 - 代扣款 已核对','分组作业消费产值 + 跨期开票差额与项目报表一致','累计数据为1月至本月逐月累加','金额单位为万元，保留2位小数','销项税额与开票系统一致（先核税额）','总账收入与开票系统一致（后核收入）','借贷方向无负数情况']],['格式与复核',['七份报表全部编制完成','截止日期、会计责任人已更新','五档逾期金额分类正确','同期对比增减值已核对','经营情况异常问题分类分工汇总已定稿','已交复核人复核']],['后续留档与催收',['项目报表签字版本已收齐（原节点5–7号）','应收账龄分析表已发项目催收']]];
function renderChecklist(){let index=0;document.getElementById('reportChecklist').innerHTML=CHECK_GROUPS.map(([title,items])=>{const start=index,body=items.map(text=>{const key='check_'+index++;return `<div class="checklist-item"><input type="checkbox" id="${key}" ${state.checklist[key]?'checked':''} onchange="toggleChecklist('${key}',this.checked)"><label for="${key}">${escapeHTML(text)}</label></div>`;}).join(''),done=items.filter((_,i)=>state.checklist['check_'+(start+i)]).length;return `<details class="check-group"><summary>${title}<span class="check-progress">${done}/${items.length}</span></summary>${body}</details>`;}).join('');}
function toggleChecklist(key,checked){if(!/^check_\d+$/.test(key))return;state.checklist[key]=!!checked;saveData();}
let activeAIReport=7;
function buildAITask(reportId=activeAIReport){const report=REPORTS.find(r=>r.id===reportId)||REPORTS[6];return `请协助办理「${report.name}」。\n工作月份：${state.activePeriod}。报表所属期、对比年份以我另行提供并确认的资料为准。\n${report.desc}\n\n要求：\n1. 先核对项目编码、数据来源、月份与金额单位；分别处理当月、累计及同期对比，缺失项列出待补充，不能按零补齐。\n2. 按既定业务口径核对营业额、代扣款、差额及增减方向；金额统一为万元、两位小数。\n3. 异常原因只依据提供的资料；没有证据的原因写“待项目确认”，不得编造。\n4. 特殊项目按我提供的原有规则处理，CF251、CF450仅在累计表填列。\n5. 输出草稿、核对清单和待确认问题，交人工复核后再定稿。\n\n此任务说明不包含财务明细，请等待我在符合公司规定的环境提供必要资料。`;}
function validAILink(value){if(!value)return '';const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)throw new Error('请使用不含账号密码的 HTTPS 软件或任务链接');return u.href;}
function openAISettings(){document.getElementById('aiSoftware').value=state.ai.software;document.getElementById('aiQianwenURL').value=state.ai.links['千问']||'';document.getElementById('aiLingxiURL').value=state.ai.links['灵犀']||'';document.getElementById('aiSettingsError').textContent='';document.getElementById('aiSettingsDialog').showModal();}
function saveAISettings(){try{const ai={software:document.getElementById('aiSoftware').value,links:{千问:validAILink(document.getElementById('aiQianwenURL').value.trim()),灵犀:validAILink(document.getElementById('aiLingxiURL').value.trim())}};if(!['千问','灵犀'].includes(ai.software))throw new Error('请选择软件');state.ai=ai;if(!saveData())throw new Error('本地保存失败，请先导出备份');document.getElementById('aiSettingsDialog').close();renderAIStatus();if(document.getElementById('aiHandoffDialog').open)updateAIHandoff();}catch(e){document.getElementById('aiSettingsError').textContent=e.message;}}
function renderAIStatus(){const el=document.getElementById('aiConfigStatus');if(el)el.textContent=state.ai.software+' · '+(state.ai.links[state.ai.software]?'已配置入口，执行情况需自行确认':'未配置链接，可手动打开软件');}
function updateAIHandoff(){
  const software=state.ai.software,link=document.getElementById('aiLaunchLink');let url='';try{url=validAILink(state.ai.links[software]||'');}catch(_){}
  link.hidden=!url;if(url)link.href=url;else link.removeAttribute('href');link.textContent='打开'+software+' →';
  document.getElementById('aiHandoffHelp').textContent=url?'复制任务要求后，点击下方链接前往'+software+'。尚未验证任务自动执行能力，请在软件中确认。':'尚未配置'+software+'链接，请复制任务要求后手动打开该软件。';
  document.getElementById('aiManualSteps').textContent='打开'+software+' → 粘贴任务要求 → 核对所属期并提供必要资料 → 执行任务 → 复核输出 → 返回工作台记录实际进度。';
  document.getElementById('aiTaskText').value=buildAITask();
}
function openAIHandoff(id=7){activeAIReport=REPORTS.some(r=>r.id===id)?id:7;updateAIHandoff();const dialog=document.getElementById('aiHandoffDialog');if(!dialog.open)dialog.showModal();}
async function copyAITask(reportId=activeAIReport){if(REPORTS.some(r=>r.id===reportId))activeAIReport=reportId;const text=buildAITask(activeAIReport);try{if(!navigator.clipboard?.writeText)throw new Error('不可用');await navigator.clipboard.writeText(text);showToast('任务要求已复制，财务资料未上传');}catch(_){const dialog=document.getElementById('aiHandoffDialog');updateAIHandoff();if(!dialog.open)dialog.showModal();const area=document.getElementById('aiTaskText');area.focus();area.select();showToast('请按 Ctrl+C 复制选中的任务要求');}}
